services:
  - type: web
    name: stewdec-backend
    runtime: node
    rootDir: Dec-main/stewDec
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 8010
    autoDeploy: true